/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2011-9-25: 17h:37m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/array.cats"
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologue from statically loaded files */
/* external codes at top */
/* type definitions */
/* external typedefs */
/* external dynamic constructor declarations */
/* external dynamic constant declarations */
extern
ats_int_type atspre_iadd (ats_int_type, ats_int_type) ;
extern
ats_int_type atspre_isub (ats_int_type, ats_int_type) ;
extern
ats_bool_type atspre_igt (ats_int_type, ats_int_type) ;
extern
ats_void_type atspre_printf_exn (ats_ptr_type, ...) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_int_type loop_1 (ats_int_type arg0, ats_int_type arg1, ats_int_type arg2) ;
static
ats_int_type fibats_0 (ats_int_type arg0) ;

/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/jeff/code/Types-and-Tests/src/fib.dats: 377(line=9, offs=7) -- 630(line=14, offs=20)
*/
ats_int_type
loop_1 (ats_int_type arg0, ats_int_type arg1, ats_int_type arg2) {
/* local vardec */
ATSlocal (ats_int_type, tmp1) ;
ATSlocal (ats_bool_type, tmp2) ;
ATSlocal (ats_int_type, tmp3) ;
ATSlocal (ats_int_type, tmp4) ;

__ats_lab_loop_1:
tmp2 = atspre_igt (arg0, 0) ;
if (tmp2) {
tmp3 = atspre_isub (arg0, 1) ;
tmp4 = atspre_iadd (arg1, arg2) ;
arg0 = tmp3 ;
arg1 = arg2 ;
arg2 = tmp4 ;
goto __ats_lab_loop_1 ; // tail call
} else {
tmp1 = arg1 ;
} /* end of [if] */
return (tmp1) ;
} /* end of [loop_1] */

/*
// /home/jeff/code/Types-and-Tests/src/fib.dats: 307(line=7, offs=5) -- 696(line=18, offs=4)
*/
ats_int_type
fibats_0 (ats_int_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp0) ;

__ats_lab_fibats_0:
tmp0 = loop_1 (arg0, 0, 1) ;
return (tmp0) ;
} /* end of [fibats_0] */

/*
// /home/jeff/code/Types-and-Tests/src/fib.dats: 732(line=20, offs=16) -- 893(line=26, offs=6)
*/
ats_void_type
mainats () {
/* local vardec */
ATSlocal_void (tmp5) ;
ATSlocal (ats_int_type, tmp6) ;
ATSlocal (ats_int_type, tmp7) ;
ATSlocal (ats_int_type, tmp8) ;
ATSlocal (ats_int_type, tmp9) ;
ATSlocal_void (tmp10) ;

__ats_lab_mainats:
tmp6 = fibats_0 (10) ;
tmp7 = ats_selsin_mac(tmp6, atslab_1) ;
tmp8 = fibats_0 (20) ;
tmp9 = ats_selsin_mac(tmp8, atslab_1) ;
/* tmp10 = */ atspre_printf_exn ((ats_ptr_type)"Fib 10 = %i\n", tmp7) ;
/* tmp5 = */ atspre_printf_exn ((ats_ptr_type)"Fib 20 = %i\n", tmp9) ;
return /* (tmp5) */ ;
} /* end of [mainats] */

/* static load function */

static int _2home_2jeff_2code_2Types_2dand_2dTests_2src_2fib_2edats__staload_flag = 0 ;

ats_void_type
_2home_2jeff_2code_2Types_2dand_2dTests_2src_2fib_2edats__staload () {
if (_2home_2jeff_2code_2Types_2dand_2dTests_2src_2fib_2edats__staload_flag) return ;
_2home_2jeff_2code_2Types_2dand_2dTests_2src_2fib_2edats__staload_flag = 1 ;
return ;
} /* staload function */
/* dynamic load function */

// (external) dynload flag declaration
// extern
// int _2home_2jeff_2code_2Types_2dand_2dTests_2src_2fib_2edats__dynload_flag ;

ats_void_type
_2home_2jeff_2code_2Types_2dand_2dTests_2src_2fib_2edats__dynload () {
// _2home_2jeff_2code_2Types_2dand_2dTests_2src_2fib_2edats__dynload_flag = 1 ;
_2home_2jeff_2code_2Types_2dand_2dTests_2src_2fib_2edats__staload () ;
#ifdef _ATS_PROOFCHECK
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

int main (int argc, char *argv[]) {
ATS_GC_INIT() ;
mainats_prelude() ;
_2home_2jeff_2code_2Types_2dand_2dTests_2src_2fib_2edats__dynload() ;
mainats((ats_int_type)argc, (ats_ptr_type)argv) ;
return (0) ;
} /* end of main */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [fib_dats.c] */
